package vu.lt.mybatis.model;

public class Account {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ACCOUNT.ID
     *
     * @mbg.generated Sun May 01 15:25:22 EEST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ACCOUNT.NUMBER
     *
     * @mbg.generated Sun May 01 15:25:22 EEST 2022
     */
    private String number;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ACCOUNT.CLIENT_ID
     *
     * @mbg.generated Sun May 01 15:25:22 EEST 2022
     */
    private Integer clientId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ACCOUNT.ID
     *
     * @return the value of PUBLIC.ACCOUNT.ID
     *
     * @mbg.generated Sun May 01 15:25:22 EEST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ACCOUNT.ID
     *
     * @param id the value for PUBLIC.ACCOUNT.ID
     *
     * @mbg.generated Sun May 01 15:25:22 EEST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ACCOUNT.NUMBER
     *
     * @return the value of PUBLIC.ACCOUNT.NUMBER
     *
     * @mbg.generated Sun May 01 15:25:22 EEST 2022
     */
    public String getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ACCOUNT.NUMBER
     *
     * @param number the value for PUBLIC.ACCOUNT.NUMBER
     *
     * @mbg.generated Sun May 01 15:25:22 EEST 2022
     */
    public void setNumber(String number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ACCOUNT.CLIENT_ID
     *
     * @return the value of PUBLIC.ACCOUNT.CLIENT_ID
     *
     * @mbg.generated Sun May 01 15:25:22 EEST 2022
     */
    public Integer getClientId() {
        return clientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ACCOUNT.CLIENT_ID
     *
     * @param clientId the value for PUBLIC.ACCOUNT.CLIENT_ID
     *
     * @mbg.generated Sun May 01 15:25:22 EEST 2022
     */
    public void setClientId(Integer clientId) {
        this.clientId = clientId;
    }
}