package vu.lt.mybatis.model;

public class ClientTeller {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CLIENT_TELLER.CLIENTS_ID
     *
     * @mbg.generated Mon May 02 21:00:37 EEST 2022
     */
    private Integer clientsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CLIENT_TELLER.TELLERS_ID
     *
     * @mbg.generated Mon May 02 21:00:37 EEST 2022
     */
    private Integer tellersId;

    private Client client;

    private Teller teller;

    public Client getClient() {
        return client;
    }

    public void setClient(Client client) {
        this.client = client;
    }

    public Teller getTeller() {
        return teller;
    }

    public void setTeller(Teller teller) {
        this.teller = teller;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CLIENT_TELLER.CLIENTS_ID
     *
     * @return the value of PUBLIC.CLIENT_TELLER.CLIENTS_ID
     *
     * @mbg.generated Mon May 02 21:00:37 EEST 2022
     */
    public Integer getClientsId() {
        return clientsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CLIENT_TELLER.CLIENTS_ID
     *
     * @param clientsId the value for PUBLIC.CLIENT_TELLER.CLIENTS_ID
     *
     * @mbg.generated Mon May 02 21:00:37 EEST 2022
     */
    public void setClientsId(Integer clientsId) {
        this.clientsId = clientsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CLIENT_TELLER.TELLERS_ID
     *
     * @return the value of PUBLIC.CLIENT_TELLER.TELLERS_ID
     *
     * @mbg.generated Mon May 02 21:00:37 EEST 2022
     */
    public Integer getTellersId() {
        return tellersId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CLIENT_TELLER.TELLERS_ID
     *
     * @param tellersId the value for PUBLIC.CLIENT_TELLER.TELLERS_ID
     *
     * @mbg.generated Mon May 02 21:00:37 EEST 2022
     */
    public void setTellersId(Integer tellersId) {
        this.tellersId = tellersId;
    }
}