package vu.lt.mybatis.model;

public class Teller {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.TELLER.ID
     *
     * @mbg.generated Mon Apr 18 14:51:50 EEST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.TELLER.DEPARTMENT
     *
     * @mbg.generated Mon Apr 18 14:51:50 EEST 2022
     */
    private Integer department;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.TELLER.NAME
     *
     * @mbg.generated Mon Apr 18 14:51:50 EEST 2022
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.TELLER.BANK_ID
     *
     * @mbg.generated Mon Apr 18 14:51:50 EEST 2022
     */
    private Integer bankId;

    private Bank bank;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.TELLER.ID
     *
     * @return the value of PUBLIC.TELLER.ID
     *
     * @mbg.generated Mon Apr 18 14:51:50 EEST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.TELLER.ID
     *
     * @param id the value for PUBLIC.TELLER.ID
     *
     * @mbg.generated Mon Apr 18 14:51:50 EEST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.TELLER.DEPARTMENT
     *
     * @return the value of PUBLIC.TELLER.DEPARTMENT
     *
     * @mbg.generated Mon Apr 18 14:51:50 EEST 2022
     */
    public Integer getDepartment() {
        return department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.TELLER.DEPARTMENT
     *
     * @param department the value for PUBLIC.TELLER.DEPARTMENT
     *
     * @mbg.generated Mon Apr 18 14:51:50 EEST 2022
     */
    public void setDepartment(Integer department) {
        this.department = department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.TELLER.NAME
     *
     * @return the value of PUBLIC.TELLER.NAME
     *
     * @mbg.generated Mon Apr 18 14:51:50 EEST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.TELLER.NAME
     *
     * @param name the value for PUBLIC.TELLER.NAME
     *
     * @mbg.generated Mon Apr 18 14:51:50 EEST 2022
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.TELLER.BANK_ID
     *
     * @return the value of PUBLIC.TELLER.BANK_ID
     *
     * @mbg.generated Mon Apr 18 14:51:50 EEST 2022
     */
    public Integer getBankId() {
        return bankId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.TELLER.BANK_ID
     *
     * @param bankId the value for PUBLIC.TELLER.BANK_ID
     *
     * @mbg.generated Mon Apr 18 14:51:50 EEST 2022
     */
    public void setBankId(Integer bankId) {
        this.bankId = bankId;
    }

    public Bank getBank() {
        return bank;
    }

    public void setBank(Bank bank) {
        this.bank = bank;
    }
}