package vu.lt.mybatis.dao;

import java.util.List;

import org.mybatis.cdi.Mapper;
import vu.lt.mybatis.model.Account;

@Mapper
public interface AccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ACCOUNT
     *
     * @mbg.generated Sun May 01 15:25:22 EEST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ACCOUNT
     *
     * @mbg.generated Sun May 01 15:25:22 EEST 2022
     */
    int insert(Account record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ACCOUNT
     *
     * @mbg.generated Sun May 01 15:25:22 EEST 2022
     */
    Account selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ACCOUNT
     *
     * @mbg.generated Sun May 01 15:25:22 EEST 2022
     */
    List<Account> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ACCOUNT
     *
     * @mbg.generated Sun May 01 15:25:22 EEST 2022
     */
    int updateByPrimaryKey(Account record);
}