package vu.lt.mybatis.dao;

import java.util.List;

import org.mybatis.cdi.Mapper;
import vu.lt.mybatis.model.ClientTeller;

@Mapper
public interface ClientTellerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CLIENT_TELLER
     *
     * @mbg.generated Mon May 02 21:00:37 EEST 2022
     */
    int insert(ClientTeller record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CLIENT_TELLER
     *
     * @mbg.generated Mon May 02 21:00:37 EEST 2022
     */
    List<ClientTeller> selectAll();
}