package vu.lt.mybatis.dao;

import java.util.List;

import org.mybatis.cdi.Mapper;
import vu.lt.mybatis.model.Client;

@Mapper
public interface ClientMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CLIENT
     *
     * @mbg.generated Sun May 01 15:25:22 EEST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CLIENT
     *
     * @mbg.generated Sun May 01 15:25:22 EEST 2022
     */
    int insert(Client record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CLIENT
     *
     * @mbg.generated Sun May 01 15:25:22 EEST 2022
     */
    Client selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CLIENT
     *
     * @mbg.generated Sun May 01 15:25:22 EEST 2022
     */
    List<Client> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CLIENT
     *
     * @mbg.generated Sun May 01 15:25:22 EEST 2022
     */
    int updateByPrimaryKey(Client record);
}